package org.protege.editor.owl.model.declaration;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.formats.RDFXMLDocumentFormat;
import org.semanticweb.owlapi.formats.TurtleDocumentFormat;
import org.semanticweb.owlapi.io.StringDocumentSource;
import org.semanticweb.owlapi.io.StringDocumentTarget;
import org.semanticweb.owlapi.model.AxiomType;
import org.semanticweb.owlapi.model.MissingImportHandlingStrategy;
import org.semanticweb.owlapi.model.OWLDeclarationAxiom;
import org.semanticweb.owlapi.model.OWLDocumentFormat;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyLoaderConfiguration;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Test support for the declaration regression corpus.
 *
 * <p>Renders a corpus ontology to RDF/XML and Turtle, reads the output back, and reports the
 * declarations the document actually carries.  Comparing declaration sets rather than document text
 * keeps the baseline blind to prefix ordering and to the OWL API's "generated by" comment, which
 * change for reasons that have nothing to do with declarations.
 *
 * <p>Rendering goes through {@code ontology.saveOntology(format, target)} rather than
 * {@code OntologySaver}, which shows a Swing progress dialog and cannot run headless.
 */
public class DeclarationBaseline {

    /**
     * Corpus members.  Two rules govern this list, and both were learned the hard way:
     *
     * <ul>
     *   <li>every member carries entities - an ontology with none cannot carry a declaration, so it
     *       cannot detect a change to declarations;</li>
     *   <li>every member renders deterministically.  {@code photography.owl} does not, and is
     *       deliberately absent: the OWL API cannot type 31 of its datatypes and mints
     *       {@code http://org.semanticweb.owlapi/error#ErrorNN} entities for them from a counter
     *       that keeps climbing for the life of the JVM.  Its declaration set therefore depends on
     *       what else the test run parsed first.</li>
     * </ul>
     */
    public static final List<String> CORPUS = Collections.unmodifiableList(Arrays.asList(
            "amino-acid.owl",
            "pizza.owl",
            "simpleLoop.owl",
            "twoEq.owl",
            "twoParents.owl"));

    public static final Path CORPUS_DIR = Paths.get("src/test/resources/declarations/corpus");

    public static final Path BASELINE_DIR = Paths.get("src/test/resources/declarations/baseline");

    /**
     * The two formats this capability governs, each with the file extension its baseline uses.
     */
    public enum Format {

        RDF_XML("rdf") {
            @Override
            OWLDocumentFormat newFormat() {
                return new RDFXMLDocumentFormat();
            }
        },

        TURTLE("ttl") {
            @Override
            OWLDocumentFormat newFormat() {
                return new TurtleDocumentFormat();
            }
        };

        private final String extension;

        Format(String extension) {
            this.extension = extension;
        }

        abstract OWLDocumentFormat newFormat();

        public String getExtension() {
            return extension;
        }
    }

    public static OWLOntology loadCorpusOntology(String fileName) throws OWLOntologyCreationException {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        manager.setOntologyLoaderConfiguration(silentAboutMissingImports());
        return manager.loadOntologyFromOntologyDocument(CORPUS_DIR.resolve(fileName).toFile());
    }

    /**
     * Renders {@code ontology} with a fresh instance of {@code format}, leaving declaration
     * synthesis at the OWL API default.
     */
    public static String render(OWLOntology ontology, Format format) throws OWLOntologyStorageException {
        StringDocumentTarget target = new StringDocumentTarget();
        ontology.saveOntology(format.newFormat(), target);
        return target.toString();
    }

    /**
     * The declarations a rendered document carries, as sorted strings.
     *
     * <p>Reading the document back is sound because the OWL API's RDF/XML and Turtle parsers report
     * exactly the declarations the document states - they do not re-invent one that the renderer
     * left out.
     */
    public static SortedSet<String> declarationsOf(String document) throws OWLOntologyCreationException {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        manager.setOntologyLoaderConfiguration(silentAboutMissingImports());
        OWLOntology parsed = manager.loadOntologyFromOntologyDocument(new StringDocumentSource(document));
        SortedSet<String> declarations = new TreeSet<>();
        for (OWLDeclarationAxiom axiom : parsed.getAxioms(AxiomType.DECLARATION)) {
            declarations.add(describe(axiom));
        }
        return declarations;
    }

    /**
     * A stable one-line form for a declaration: entity type and IRI, so a baseline diff names the
     * term that moved.
     */
    public static String describe(OWLDeclarationAxiom axiom) {
        return axiom.getEntity().getEntityType().getName() + " " + axiom.getEntity().getIRI();
    }

    public static SortedSet<String> baselineDeclarations(String ontologyFileName, Format format)
            throws OWLOntologyCreationException, IOException {
        return declarationsOf(readBaseline(ontologyFileName, format));
    }

    public static Path baselinePath(String ontologyFileName, Format format) {
        String stem = ontologyFileName.replaceAll("\\.owl$", "");
        return BASELINE_DIR.resolve(stem + "." + format.getExtension());
    }

    public static String readBaseline(String ontologyFileName, Format format) throws IOException {
        return new String(Files.readAllBytes(baselinePath(ontologyFileName, format)), StandardCharsets.UTF_8);
    }

    private static OWLOntologyLoaderConfiguration silentAboutMissingImports() {
        return new OWLOntologyLoaderConfiguration()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);
    }

    /**
     * Regenerates every baseline document from the corpus.
     *
     * <p>Read {@code src/test/resources/declarations/README.md} before running this.  A baseline
     * diff is a finding to explain, not a file to overwrite.
     */
    public static void main(String[] args) throws Exception {
        Files.createDirectories(BASELINE_DIR);
        List<String> written = new ArrayList<>();
        for (String ontologyFileName : CORPUS) {
            OWLOntology ontology = loadCorpusOntology(ontologyFileName);
            for (Format format : Format.values()) {
                Path target = baselinePath(ontologyFileName, format);
                Files.write(target, render(ontology, format).getBytes(StandardCharsets.UTF_8));
                written.add(target.toString());
            }
        }
        for (String path : written) {
            System.out.println("wrote " + path);
        }
        System.out.println("Regenerated " + written.size() + " baseline documents.");
    }

    private DeclarationBaseline() {
    }

    static {
        // Fail loudly if the corpus directory has gone missing, rather than reporting an empty
        // baseline as a pass.
        File corpusDir = CORPUS_DIR.toFile();
        if (!corpusDir.isDirectory()) {
            throw new IllegalStateException("Corpus directory not found: " + corpusDir.getAbsolutePath());
        }
    }
}
